services:
  nasam-tenant-rpc:
    image: ghcr.io/nasam-main/nasam-tenant-rpc:staging
    container_name: nasam-tenant-rpc-staging
    restart: unless-stopped
    networks:
      - nasam-stage-network

networks:
  nasam-stage-network:
    external: true
    name: nasam-v2-api-stage_nasam-stage-network
